
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=1.21.1

minecraft_version_range=[1.21.1,1.22)

neo_version=21.1.219

neo_version_range=[21,)

loader_version_range=[4,)
# The Minecraft version the Parchment version is for
neoForge.parchment.minecraftVersion=1.21.1
# The version of the Parchment mappings
neoForge.parchment.mappingsVersion=2024.11.17

mixin_version = 0.8.5
mixin_extras_version = 0.4.1


jei_minecraft_version = 1.21.1
jei_version = 19.25.0.322
create_version = 6.0.10-280
ponder_version = 1.0.82
flywheel_version = 1.0.6
registrate_version = MC1.21-1.3.0+67

mod_id=tfmg
mod_name=Create: The Factory Must Grow
mod_license=MIT
mod_version=1.2.2
mod_group_id=com.drmangotea
mod_authors= DrMangoTea, Pepa, Luna
mod_description= Create: The Factory Must Grow brings the age of steel, oil and electricity to the Create mod
